# Generated by Django 2.0.2 on 2018-02-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k2k', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='item_media',
            new_name='ItemMedia',
        ),
        migrations.DeleteModel(
            name='order_item',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='itemmedia',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(to='k2k.Color'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(to='k2k.Size'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k2k.Item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k2k.Order'),
        ),
    ]
