# Generated by Django 2.0.2 on 2018-02-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k2k', '0002_auto_20180218_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='color',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='size',
            new_name='sizes',
        ),
        migrations.AlterField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(to='k2k.Color'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(to='k2k.Size'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k2k.Order'),
        ),
    ]
