# Generated by Django 2.0.2 on 2018-03-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k2k', '0008_auto_20180306_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(default=None, null=True, to='k2k.Color'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(default=None, null=True, to='k2k.Size'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k2k.Order'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='k2k.Category'),
        ),
    ]
